# Generated by Django 5.2.6 on 2025-09-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
